# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enteryPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import guestPanel
import managerLogin


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(674, 443)
        Form.setStyleSheet("background-color: rgb(237, 246, 249);")
        self.managerButton = QtWidgets.QPushButton(Form)
        self.managerButton.setGeometry(QtCore.QRect(80, 130, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Fredoka")
        font.setPointSize(14)
        self.managerButton.setFont(font)
        self.managerButton.setStyleSheet("background-color: rgb(226, 149, 120);\n"
        "border-radius: 25px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.managerButton.setIcon(icon)
        self.managerButton.setIconSize(QtCore.QSize(35, 35))
        self.managerButton.setObjectName("managerButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 30, 500, 41))
        font = QtGui.QFont()
        font.setFamily("Big John")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(260, 80, 500, 331))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images/hotel.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.guestButton = QtWidgets.QPushButton(Form)
        self.guestButton.setGeometry(QtCore.QRect(80, 270, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Fredoka")
        font.setPointSize(14)
        self.guestButton.setFont(font)
        self.guestButton.setStyleSheet("background-color: rgb(226, 149, 120);\n"
        "border-radius: 25px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/guest.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.guestButton.setIcon(icon1)
        self.guestButton.setIconSize(QtCore.QSize(35, 35))
        self.guestButton.setObjectName("guestButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # Connect the 'guestButton' to the 'open_guestPanel' method to open the guest panel.
        self.guestButton.clicked.connect(self.open_guestPanel)
        # Connect the 'managerButton' to the 'open_managerPanel' method to open the manager login panel.
        self.managerButton.clicked.connect(self.open_managerPanel)

    def open_guestPanel(self):
        # Create a new QWidget instance for the guest panel window.
        self.window = QtWidgets.QWidget()
        # Instantiate the Ui_guestPanel class to setup the user interface for the guest panel.
        self.ui = guestPanel.Ui_guestPanel()
        # Set up the user interface for the guest panel.
        self.ui.setupUi(self.window)
        # Display the guest panel window to the user.
        self.window.show()

    def open_managerPanel(self):
        # Create a new QWidget instance for the manager login panel window.
        self.window = QtWidgets.QWidget()
        # Instantiate the Ui_managerLogin class to setup the user interface for the manager login panel.
        self.ui = managerLogin.Ui_managerLogin()
        # Set up the user interface for the manager login panel.
        self.ui.setupUi(self.window)
        # Display the manager login panel window to the user.
        self.window.show()

    
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Hotel Management System"))
        self.managerButton.setText(_translate("Form", "Manager"))
        self.label.setText(_translate("Form", "Hotel Management System"))
        self.guestButton.setText(_translate("Form", "Guest"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
