# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'managerLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import managersPanel


class Ui_managerLogin(object):
    def setupUi(self, managerLogin):
        managerLogin.setObjectName("managerLogin")
        managerLogin.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        managerLogin.setWindowIcon(icon)
        managerLogin.setStyleSheet("background-color: rgb(237, 246, 249);")
        self.pushButton = QtWidgets.QPushButton(managerLogin)
        self.pushButton.setGeometry(QtCore.QRect(140, 230, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Fredoka Light")
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(226, 149, 120);\n"
"border-radius: 25px;")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(managerLogin)
        self.label.setGeometry(QtCore.QRect(60, 20, 280, 41))
        font = QtGui.QFont()
        font.setFamily("Big John")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(managerLogin)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 100, 341, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.userNameLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(9)
        self.userNameLine.setFont(font)
        self.userNameLine.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.userNameLine.setObjectName("userNameLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userNameLine)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.passwordLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(9)
        self.passwordLine.setFont(font)
        self.passwordLine.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.passwordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLine.setObjectName("passwordLine")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.passwordLine)
        self.failedUsername = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(9)
        self.failedUsername.setFont(font)
        self.failedUsername.setStyleSheet("color: red;")
        self.failedUsername.setText("")
        self.failedUsername.setObjectName("failedUsername")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.failedUsername)
        self.failedPassword = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(9)
        self.failedPassword.setFont(font)
        self.failedPassword.setStyleSheet("color: red;")
        self.failedPassword.setText("")
        self.failedPassword.setObjectName("failedPassword")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.failedPassword)

        self.retranslateUi(managerLogin)
        QtCore.QMetaObject.connectSlotsByName(managerLogin)

        self.managerLogin = managerLogin
        # Connect the 'pushButton' to the 'login' method for user authentication.
        self.pushButton.clicked.connect(self.login)

    def login(self):
        # Retrieve the text from the username and password input fields.
        entered_username = self.userNameLine.text()
        entered_password = self.passwordLine.text()
        
        # Check if both username and password are correct.
        if entered_username == "Minou" and entered_password == "@Min1378":
            # Set the text and color of the failedUsername and failedPassword labels to indicate successful login.
            self.failedUsername.setText("Correct")
            self.failedPassword.setText("Correct")
            self.failedUsername.setStyleSheet("color: green;")
            self.failedPassword.setStyleSheet("color: green;")
            
            # Close the current manager login window.
            self.managerLogin.close()
            
            # Create a new QWidget instance for the manager panel window.
            self.window = QtWidgets.QWidget()
            # Instantiate the Ui_managersPanel class to set up the user interface for the manager panel.
            self.ui = managersPanel.Ui_managersPanel()
            # Set up the user interface for the manager panel.
            self.ui.setupUi(self.window)
            # Display the manager panel window to the user.
            self.window.show()

        # Check if the username is incorrect but the password is correct.
        elif entered_username != "Minou" and entered_password == "@Min1378":
            # Set the text and color of the failedUsername label to indicate a wrong username.
            self.failedUsername.setStyleSheet("color: red;")
            self.failedUsername.setText("Wrong Username!")
            # Set the text and color of the failedPassword label to indicate the correct password.
            self.failedPassword.setText("Correct")
            self.failedPassword.setStyleSheet("color: green;")

        # Check if the username is correct but the password is incorrect.
        elif entered_username == "Minou" and entered_password != "@Min1378":
            # Set the text and color of the failedUsername label to indicate the correct username.
            self.failedUsername.setText("Correct")
            self.failedUsername.setStyleSheet("color: green;")
            # Set the text and color of the failedPassword label to indicate a wrong password.
            self.failedPassword.setText("Wrong Password!")
            self.failedPassword.setStyleSheet("color: red;")

        # Check if both the username and password are incorrect.
        elif entered_username != "Minou" and entered_password != "@Min1378":
            # Set the text and color of both the failedUsername and failedPassword labels to indicate wrong credentials.
            self.failedUsername.setText("Wrong Username!")
            self.failedPassword.setText("Wrong Password!")
            self.failedUsername.setStyleSheet("color: red;")
            self.failedPassword.setStyleSheet("color: red;")


    def retranslateUi(self, managerLogin):
        _translate = QtCore.QCoreApplication.translate
        managerLogin.setWindowTitle(_translate("managerLogin", "Mager Login"))
        self.pushButton.setText(_translate("managerLogin", "Log In"))
        self.label.setText(_translate("managerLogin", "Manager Log-In"))
        self.label_2.setText(_translate("managerLogin", "Username:"))
        self.label_3.setText(_translate("managerLogin", "Password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    managerLogin = QtWidgets.QWidget()
    ui = Ui_managerLogin()
    ui.setupUi(managerLogin)
    managerLogin.show()
    sys.exit(app.exec_())
