# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\managersPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import guestPanel
import searchGuest
import guestList
import checkOut


class Ui_managersPanel(object):
    def setupUi(self, managersPanel):
        managersPanel.setObjectName("managersPanel")
        managersPanel.resize(550, 550)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Images/manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        managersPanel.setWindowIcon(icon)
        managersPanel.setStyleSheet("background-color: rgb(237, 246, 249);")
        self.checkInButton = QtWidgets.QPushButton(managersPanel)
        self.checkInButton.setGeometry(QtCore.QRect(50, 30, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Fredoka Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.checkInButton.setFont(font)
        self.checkInButton.setStyleSheet("background-color: rgb(243, 145, 137);")
        self.checkInButton.setObjectName("checkInButton")
        self.guestListButton = QtWidgets.QPushButton(managersPanel)
        self.guestListButton.setGeometry(QtCore.QRect(50, 130, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Fredoka Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.guestListButton.setFont(font)
        self.guestListButton.setStyleSheet("background-color: rgb(243, 145, 137);")
        self.guestListButton.setObjectName("guestListButton")
        self.checkOutButton = QtWidgets.QPushButton(managersPanel)
        self.checkOutButton.setGeometry(QtCore.QRect(50, 330, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Fredoka Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.checkOutButton.setFont(font)
        self.checkOutButton.setStyleSheet("background-color: rgb(243, 145, 137);")
        self.checkOutButton.setObjectName("checkOutButton")
        self.searchGuestButton = QtWidgets.QPushButton(managersPanel)
        self.searchGuestButton.setGeometry(QtCore.QRect(50, 230, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Fredoka Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.searchGuestButton.setFont(font)
        self.searchGuestButton.setStyleSheet("background-color: rgb(243, 145, 137);")
        self.searchGuestButton.setObjectName("searchGuestButton")
        self.exitButton = QtWidgets.QPushButton(managersPanel)
        self.exitButton.setGeometry(QtCore.QRect(50, 430, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Fredoka Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("background-color: rgb(243, 145, 137);")
        self.exitButton.setObjectName("exitButton")
        self.label = QtWidgets.QLabel(managersPanel)
        self.label.setGeometry(QtCore.QRect(280, 150, 251, 251))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap(".\\Images/accountant (1).png"))
        self.label.setObjectName("label")

        self.retranslateUi(managersPanel)
        QtCore.QMetaObject.connectSlotsByName(managersPanel)
        
        # Connect the 'checkInButton' to the 'openCheckIn' method to open the check-in panel.
        self.checkInButton.clicked.connect(self.openCheckIn)
        # Connect the 'exitButton' to the 'closePage' method to close the manager panel.
        self.exitButton.clicked.connect(self.closePage)
        # Connect the 'searchGuestButton' to the 'searchGuest' method to open the search guest panel.
        self.searchGuestButton.clicked.connect(self.searchGuest)
        # Connect the 'guestListButton' to the 'guestInfo' method to open the guest list panel.
        self.guestListButton.clicked.connect(self.guestInfo)
        # Connect the 'checkOutButton' to the 'checkOutGuest' method to open the check-out panel.
        self.checkOutButton.clicked.connect(self.checkOutGuest)

        # Store a reference to the managersPanel for future access.
        self.managersPanel = managersPanel

    def openCheckIn(self):
        # Create a new QWidget instance for the check-in panel window.
        self.window = QtWidgets.QWidget()
        # Instantiate the Ui_guestPanel class to setup the user interface for the check-in panel.
        self.ui = guestPanel.Ui_guestPanel()
        # Set up the user interface for the check-in panel.
        self.ui.setupUi(self.window)
        # Display the check-in panel window to the user.
        self.window.show()

    def searchGuest(self):
        # Create a new QWidget instance for the search guest panel window.
        self.window = QtWidgets.QWidget()
        # Instantiate the Ui_searchGuest class to setup the user interface for the search guest panel.
        self.ui = searchGuest.Ui_searchGuest()
        # Set up the user interface for the search guest panel.
        self.ui.setupUi(self.window)
        # Display the search guest panel window to the user.
        self.window.show()

    def guestInfo(self):
        # Create a new QWidget instance for the guest list panel window.
        self.window = QtWidgets.QWidget()
        # Instantiate the Ui_guestsList class to setup the user interface for the guest list panel.
        self.ui = guestList.Ui_guestsList()
        # Set up the user interface for the guest list panel.
        self.ui.setupUi(self.window)
        # Display the guest list panel window to the user.
        self.window.show()

    def checkOutGuest(self):
        # Create a new QWidget instance for the check-out panel window.
        self.window = QtWidgets.QWidget()
        # Instantiate the Ui_checkOut class to setup the user interface for the check-out panel.
        self.ui = checkOut.Ui_checkOut()
        # Set up the user interface for the check-out panel.
        self.ui.setupUi(self.window)
        # Display the check-out panel window to the user.
        self.window.show()

    def closePage(self):
        # Close the manager panel window.
        self.managersPanel.close()

    
    
    
    def retranslateUi(self, managersPanel):
        _translate = QtCore.QCoreApplication.translate
        managersPanel.setWindowTitle(_translate("managersPanel", "Manager\'s Page"))
        self.checkInButton.setText(_translate("managersPanel", "Check In"))
        self.guestListButton.setText(_translate("managersPanel", "List of the Guest"))
        self.checkOutButton.setText(_translate("managersPanel", "Check Out"))
        self.searchGuestButton.setText(_translate("managersPanel", "Search for a Guest"))
        self.exitButton.setText(_translate("managersPanel", "Exit"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    managersPanel = QtWidgets.QWidget()
    ui = Ui_managersPanel()
    ui.setupUi(managersPanel)
    managersPanel.show()
    sys.exit(app.exec_())
